name: GriefPreventionFlags
version: 1.2
main: src.john01dav.GriefPreventionFlags.GriefPreventionFlags
depend: [GriefPrevention]

commands:
  setFlag:
    description: Allows you to set a flag for a claim!
    permission: griefpreventionflags.setflag
    usage: /setflag <flag> <value>
  setFlagGlobal:
    description: Allows you to set a flag globally
    permission: griefpreventionflags.setflag.global
    usage: /setflagglobal <flag> <value>