name: GriefPreventionFlags
version: 1.0.1
main: src.john01dav.GriefPreventionFlags.GriefPreventionFlags
depend: [GriefPrevention]

commands:
  setFlag:
    description: Allows you to set a flag for a claim!
    permission: griefpreventionflags.setflag
    usage: /setflag <flag> <value>